/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign8;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  ALTERNATIVE, CONTACT_BANNER, CONTACT_BUTTON, DEALER_PHONE, GET_DIRECTIONS, BADGES, TEST_DRIVE_LINK, ERROR, SUCCESS, CONTACT_FORM, MARKET_REPORT, BADGE_DETAIL, PHOTO_MODAL, FEATURES, VEHICLE_HISTORY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign8\",\"symbols\":[\"ALTERNATIVE\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"DEALER_PHONE\",\"GET_DIRECTIONS\",\"BADGES\",\"TEST_DRIVE_LINK\",\"ERROR\",\"SUCCESS\",\"CONTACT_FORM\",\"MARKET_REPORT\",\"BADGE_DETAIL\",\"PHOTO_MODAL\",\"FEATURES\",\"VEHICLE_HISTORY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
